# Generated by Django 4.1.3 on 2022-11-24 23:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('scryfall_uri', models.URLField()),
                ('scryfall_url', models.URLField()),
                ('layout', models.CharField(choices=[('NORMAL', 'normal'), ('SPLIT', 'split'), ('FLIP', 'flip'), ('TRANSFORM', 'transform'), ('MODAL_DFC', 'modal_dfc'), ('MELD', 'meld'), ('LEVELER', 'leveler'), ('CLASS', 'class'), ('SAGA', 'saga'), ('ADVENTURE', 'adventure'), ('PLANAR', 'planar'), ('SCHEME', 'scheme'), ('VANGUARD', 'vanguard'), ('TOKEN', 'token'), ('DOUBLE_FACED_TOKEN', 'double_faced_token'), ('EMBLEM', 'emblem'), ('AUGMENT', 'augment'), ('HOST', 'host'), ('ART_SERIES', 'art_series'), ('REVERSIBLE_CARD', 'reversible_card')], max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('conv_mana_cost', models.IntegerField()),
                ('released_at', models.DateField(default=datetime.date(1993, 9, 1))),
                ('time_added_to_db', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('symbol', models.CharField(max_length=8)),
                ('set_type', models.CharField(max_length=20)),
                ('scryfall_uri', models.URLField()),
                ('scryfall_set_cards_uri', models.URLField()),
                ('icon_uri', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cards', models.ManyToManyField(to='common.card')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.storagelocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('price_usd_foil', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('price_usd_etched', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('price_tix', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('price_eur_foil', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_type', models.CharField(choices=[('NORMAL', 'normal'), ('FOIL', 'foil'), ('ETCHED', 'etched')], default='normal', max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(null=True)),
                ('price_purchased', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mana_cost', models.JSONField()),
                ('power', models.SmallIntegerField(null=True)),
                ('toughness', models.SmallIntegerField(null=True)),
                ('type_line', models.CharField(max_length=256, null=True)),
                ('oracle_text', models.CharField(max_length=1500, null=True)),
                ('small_img_uri', models.URLField(null=True)),
                ('normal_img_uri', models.URLField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.cardset'),
        ),
        migrations.CreateModel(
            name='ConstructedDeck',
            fields=[
                ('deck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.deck')),
                ('format_name', models.CharField(choices=[('Standard', 'standard'), ('Modern', 'modern'), ('Pioneer', 'pioneer'), ('Historic', 'historic'), ('Legacy', 'legacy'), ('Vintage', 'vintage'), ('Pauper', 'pauper')], max_length=15)),
                ('sideboard', models.ManyToManyField(to='common.card')),
            ],
            bases=('common.deck',),
        ),
        migrations.CreateModel(
            name='CommanderDeck',
            fields=[
                ('deck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.deck')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commander', to='common.card')),
                ('secondary_commander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_commander', to='common.card')),
            ],
            bases=('common.deck',),
        ),
    ]
