# Generated by Django 4.1.3 on 2022-11-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_cardface_mana_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cardset',
            old_name='scryfall_uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cardface',
            name='normal_img_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='small_img_uri',
            field=models.URLField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('id', 'printing_type')},
        ),
    ]
