# Generated by Django 4.1.3 on 2022-11-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_uuid_card_id_rename_scryfall_uuid_cardset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='oracle_text',
            field=models.CharField(max_length=1500),
        ),
    ]
