# Generated by Django 4.1.3 on 2022-11-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_cardface_oracle_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='oracle_text',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='type_line',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
