# Generated by Django 4.1.3 on 2022-11-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_cardface_oracle_text_alter_cardface_type_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='type_line',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
