# Generated by Django 4.1.3 on 2022-11-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_cardface_name_alter_cardface_type_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='face_primary',
        ),
        migrations.RemoveField(
            model_name='card',
            name='face_secondary',
        ),
        migrations.AddField(
            model_name='cardface',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='common.card'),
            preserve_default=False,
        ),
    ]
